export const MSG_ADD_TO_CART_SUCCES = 'Mua Hàng Thành Công'
export const MSG_UPDATE_CART_SUCCES = 'Cập Nhật Giỏ Hàng Thành Công'
export const MSG_DELETE_PRODUCT_IN_CART_SUCCES = 'Xóa Sản Phẩm Khỏi Giỏ Hàng Thành Công'
export const MSG_CART_EMPTY = 'Chưa Có Sản Phẩm Trong Giỏ Hàng'
export const MSG_WELCOME = 'Chào Mừng Các Bạn'